# Generated by Django 4.1.2 on 2022-11-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursiones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursiones',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='paisaje'),
        ),
    ]
